### ISSUE TITLE
Improve research track illustrations

### ISSUE THREAD

**Issue by coyotte508** [donkeytech/gaia-viewer#82]
I recently added visual aids (income, qic, ...) on research tracks. Design is not the best.

**Comment by rzulian** [comment]
Display 1 for single gain (e.g. 1 QIC).
Keep consistent order for resources, otherwise is difficult to read and also doesn't look nice
<img width="73" alt="screen shot 2018-09-16 at 10 59 51" src="https://user-images.githubusercontent.com/29941924/45594736-817fa480-b96d-11e8-909f-ae65b16b2ba9.png">

If displaying illustrations I would move it below the players' tokens. BTW, and probably a better way, I would keep player token in one row
<img width="65" alt="screen shot 2018-09-16 at 11 01 54" src="https://user-images.githubusercontent.com/29941924/45594743-bab81480-b96d-11e8-8dd4-0f0cd33c5a29.png">

**Comment by rzulian** [comment]
<img width="322" alt="screen shot 2018-09-16 at 12 12 14" src="https://user-images.githubusercontent.com/29941924/45596998-409a8680-b993-11e8-8bd6-31060ac2ef84.png">
Is not that bad.
BTW. I've received feedback on the color schema. Particulary the blu.

**Comment by coyotte508** [comment]
Go ahead with the colors & tokens! They do look more distinct

**Comment by coyotte508** [comment]
The nav & cost labels should have `pointer-events: none`
